package com.jidedaizhijin.myapplication

import android.content.Context
import android.provider.MediaStore
import com.jidedaizhijin.myapplication.data.lyrics.LocalLyricsParser
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

object LyricsRepository {

    private const val FOOTER_FORMATTED = "Lyrics formatted by AI"
    private const val FOOTER_GENERATED = "Lyrics generated by AI"
    private const val FOOTER_FAILED = "AI failed"

    suspend fun getLyrics(
        context: Context,
        songId: Long,
        title: String,
        artist: String,
        forceRefresh: Boolean = false
    ): String {

        val apiKey = ApiSettingsStore.getApiKey(context)
        val baseUrl = ApiSettingsStore.getBaseUrl(context)
        val model = ApiSettingsStore.getModel(context)

        if (!forceRefresh) {
            val cache = getCache(context, songId)
            if (cache.isNotBlank() && !isFailureText(cache)) {
                return cache
            }
        }

        val localLyrics = loadLocalLyrics(context, songId)
        if (!localLyrics.isNullOrBlank()) {
            val result = cleanLyricsForDisplay(localLyrics)
            saveIfMeaningful(context, songId, result)
            return result
        }

        val embeddedLyrics = loadEmbeddedMp3Lyrics(context, songId)
        if (!embeddedLyrics.isNullOrBlank()) {
            val result = cleanLyricsForDisplay(embeddedLyrics)
            saveIfMeaningful(context, songId, result)
            return result
        }

        if (apiKey.isBlank()) {
            return "No lyrics"
        }

        val rawLyrics = AiLyricsProvider.fetchLyrics(
            apiKey = apiKey,
            baseUrl = baseUrl,
            model = model,
            title = title,
            artist = artist
        ).trim()

        val finalText = if (rawLyrics.isNotBlank()) {
            buildAiLyricsResult(
                apiKey = apiKey,
                baseUrl = baseUrl,
                model = model,
                rawLyrics = rawLyrics,
                title = title,
                artist = artist,
                footer = FOOTER_GENERATED
            )
        } else {
            "No lyrics\n\n$FOOTER_FAILED"
        }

        saveIfMeaningful(context, songId, finalText)
        return finalText
    }

    suspend fun refreshLyrics(
        context: Context,
        songId: Long,
        title: String,
        artist: String
    ): String {

        val apiKey = ApiSettingsStore.getApiKey(context)
        val baseUrl = ApiSettingsStore.getBaseUrl(context)
        val model = ApiSettingsStore.getModel(context)

        val localLyrics = loadLocalLyrics(context, songId)
        val embeddedLyrics = loadEmbeddedMp3Lyrics(context, songId)
        val cachedLyrics = getCache(context, songId)

        val currentLyricsBody = when {
            !localLyrics.isNullOrBlank() -> cleanLyricsForDisplay(localLyrics)
            !embeddedLyrics.isNullOrBlank() -> cleanLyricsForDisplay(embeddedLyrics)
            cachedLyrics.isNotBlank() && !isFailureText(cachedLyrics) -> extractLyricsBodyFromCache(cachedLyrics)
            else -> ""
        }

        clearCache(context, songId)

        if (currentLyricsBody.isNotBlank()) {
            if (apiKey.isBlank()) {
                saveIfMeaningful(context, songId, currentLyricsBody)
                return currentLyricsBody
            }

            val aiResult = buildAiLyricsResult(
                apiKey = apiKey,
                baseUrl = baseUrl,
                model = model,
                rawLyrics = currentLyricsBody,
                title = title,
                artist = artist,
                footer = FOOTER_FORMATTED
            )

            val finalText = if (aiResult.isNotBlank() && !isFailureText(aiResult)) {
                aiResult
            } else {
                currentLyricsBody
            }

            saveIfMeaningful(context, songId, finalText)
            return finalText
        }

        if (apiKey.isNotBlank()) {
            val fetchedLyrics = AiLyricsProvider.fetchLyrics(
                apiKey = apiKey,
                baseUrl = baseUrl,
                model = model,
                title = title,
                artist = artist
            ).trim()

            if (fetchedLyrics.isNotBlank()) {
                val finalText = buildAiLyricsResult(
                    apiKey = apiKey,
                    baseUrl = baseUrl,
                    model = model,
                    rawLyrics = fetchedLyrics,
                    title = title,
                    artist = artist,
                    footer = FOOTER_GENERATED
                )
                saveIfMeaningful(context, songId, finalText)
                return finalText
            }
        }

        val fallbackText = when {
            !localLyrics.isNullOrBlank() -> cleanLyricsForDisplay(localLyrics)
            !embeddedLyrics.isNullOrBlank() -> cleanLyricsForDisplay(embeddedLyrics)
            cachedLyrics.isNotBlank() && !isFailureText(cachedLyrics) -> extractLyricsBodyFromCache(cachedLyrics)
            apiKey.isNotBlank() -> "No lyrics\n\n$FOOTER_FAILED"
            else -> "No lyrics"
        }

        saveIfMeaningful(context, songId, fallbackText)
        return fallbackText
    }

    private suspend fun buildAiLyricsResult(
        apiKey: String,
        baseUrl: String,
        model: String,
        rawLyrics: String,
        title: String,
        artist: String,
        footer: String
    ): String {

        val (body, existingHighlightLine) = splitHighlight(rawLyrics)
        val sourceBody = body.ifBlank { rawLyrics }.trim()

        val formattedBody = AiLyricsProvider.formatLyrics(
            apiKey = apiKey,
            baseUrl = baseUrl,
            model = model,
            rawLyrics = sourceBody
        ).trim().ifBlank { sourceBody }

        val cleanedBody = cleanLyricsForDisplay(formattedBody)

        val finalHighlight = existingHighlightLine?.takeIf { it.isNotBlank() }
            ?: buildHighlightLine(
                apiKey = apiKey,
                baseUrl = baseUrl,
                model = model,
                title = title,
                artist = artist,
                lyricsBody = cleanedBody
            )

        return buildString {
            append(cleanedBody)

            if (!finalHighlight.isNullOrBlank()) {
                append("\n\n")
                append(finalHighlight)
            }

            if (cleanedBody.isNotBlank() && cleanedBody != "No lyrics") {
                append("\n\n")
                append(footer)
            }
        }.trim()
    }

    private fun isFailureText(text: String): Boolean {
        return text == "No lyrics" || text.contains(FOOTER_FAILED)
    }

    private suspend fun saveIfMeaningful(
        context: Context,
        songId: Long,
        text: String
    ) {
        if (
            text.isNotBlank() &&
            text != "No lyrics" &&
            !text.contains(FOOTER_FAILED)
        ) {
            saveCache(context, songId, text)
        }
    }

    private fun extractLyricsBodyFromCache(text: String): String {
        val (body, _) = splitHighlight(text)

        return body.lines()
            .map { it.trim() }
            .filter {
                it.isNotBlank() &&
                        it != FOOTER_FORMATTED &&
                        it != FOOTER_GENERATED &&
                        it != FOOTER_FAILED
            }
            .joinToString("\n")
            .trim()
    }

    private fun cleanLyricsForDisplay(text: String): String {
        if (text.isBlank()) return ""

        return text
            .replace(Regex("""\[\d{2}:\d{2}(?:\.\d{2,3})?]"""), "")
            .lines()
            .map { it.trim() }
            .filter { it.isNotBlank() }
            .joinToString("\n")
            .replace(Regex("\n{3,}"), "\n\n")
            .trim()
    }

    private suspend fun buildHighlightLine(
        apiKey: String,
        baseUrl: String,
        model: String,
        title: String,
        artist: String,
        lyricsBody: String
    ): String {

        val highlight = if (apiKey.isNotBlank()) {
            AiLyricsProvider.generateHighlight(
                apiKey = apiKey,
                baseUrl = baseUrl,
                model = model,
                title = title,
                artist = artist,
                lyrics = lyricsBody
            ).trim()
        } else {
            AiLyricsProvider.buildFallbackHighlight(title, artist)
        }

        val finalText = highlight.ifBlank {
            AiLyricsProvider.buildFallbackHighlight(title, artist)
        }.trim()

        return if (finalText.isNotBlank()) "✨ $finalText" else ""
    }

    private fun splitHighlight(text: String): Pair<String, String?> {
        val lines = text.lines().map { it.trim() }

        val highlightLine = lines.firstOrNull { it.startsWith("✨") }?.trim()

        val body = lines
            .filter { it.isNotBlank() && !it.startsWith("✨") }
            .joinToString("\n")
            .trim()

        return body to highlightLine
    }

    private fun findSongFilePathById(context: Context, songId: Long): String? {
        return try {
            val uri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI
            val projection = arrayOf(MediaStore.Audio.Media.DATA)
            val selection = "${MediaStore.Audio.Media._ID}=?"
            val args = arrayOf(songId.toString())

            context.contentResolver.query(
                uri,
                projection,
                selection,
                args,
                null
            )?.use { cursor ->
                val dataCol = cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.DATA)

                if (cursor.moveToFirst()) {
                    cursor.getString(dataCol)
                } else {
                    null
                }
            }
        } catch (_: Exception) {
            null
        }
    }

    private fun loadEmbeddedMp3Lyrics(context: Context, songId: Long): String? {
        val filePath = findSongFilePathById(context, songId)

        return Mp3EmbeddedLyricsReader.readLyrics(filePath)
            ?.trim()
            ?.ifBlank { null }
    }

    private fun loadLocalLyrics(context: Context, songId: Long): String? {
        val filePath = findSongFilePathById(context, songId)
        val lrcText = LocalLyricsParser.readLrcFileIfExists(filePath) ?: return null
        val parsed = LocalLyricsParser.parseLrcText(lrcText)

        return if (parsed.isNotEmpty()) {
            parsed.joinToString("\n") { it.text }
        } else {
            lrcText.trim().ifBlank { null }
        }
    }

    private suspend fun getCache(context: Context, songId: Long): String =
        withContext(Dispatchers.IO) {
            context.getSharedPreferences("lyrics_cache", Context.MODE_PRIVATE)
                .getString("lyrics_$songId", "") ?: ""
        }

    private suspend fun saveCache(context: Context, songId: Long, lyrics: String) =
        withContext(Dispatchers.IO) {
            context.getSharedPreferences("lyrics_cache", Context.MODE_PRIVATE)
                .edit()
                .putString("lyrics_$songId", lyrics)
                .apply()
        }

    private suspend fun clearCache(context: Context, songId: Long) =
        withContext(Dispatchers.IO) {
            context.getSharedPreferences("lyrics_cache", Context.MODE_PRIVATE)
                .edit()
                .remove("lyrics_$songId")
                .apply()
        }
}